# linux_common variables
LC_CHANGE_HOSTNAME: False
#ansible_user_id: "" # set to the ssh user
#inventory_hostname_short: ""
LC_SET_LOCALES: False
LC_SETUP_SUDO: False
LC_LOCALES:
  - "en_US ISO-8859-1"
  - "en_US.ISO-8859-15 ISO-8859-15"
  - "en_US.UTF-8 UTF-8"
LC_DEFAULT_LOCALE: "en_US.UTF-8 UTF-8"
LC_MODIFY_SYSTEM_SHELL_ENV: True
LC_MODIFY_SKEL: True
LC_MODIFY_ROOT_SHELL_ENV: True
LC_MODIFY_USER_SHELL_ENV: True
LC_DEBIAN_MIRROR: "deb.debian.org"
LC_INSTALL_PACKAGES: True
LC_REBOOT: False
LC_CHANGE_TIMEZONE: False
LC_ENABLE_SRC_REPOS: False
LC_ENABLE_APT_BACKPORTS: False
LC_CHANGES_APT_DEFAULT_SOURCES_LIST: False
LC_TIMEZONE: "Asia/Karachi"
LC_SET_KERNEL_PARAMETERS: True
LC_KERNEL_PARAMETERS:
  - { name: "vm.swappiness", value: 1, state: present }
  - { name: "vm.vfs_cache_pressure", value: 50, state: present }
  - { name: "net.ipv4.tcp_timestamps", value: 0, state: present }
  - { name: "fs.inotify.max_user_watches", value: 524288, state: present }
  - { name: "fs.inotify.max_user_instances", value: 524288, state: present }
  - { name: "net.ipv4.ip_forward", value: 1, state: present }
LC_EXTRA_PACKAGES:
  - "gpg"
  - "apt-transport-https"
  - "podman"

# motd variables
memory_info: False
network_info: True

# acme variables
ACME_GIT_VERSION: "3.0.6"
ACME_DOMAINS:
  PRIMARY: "{{ ACME_DOMAIN_NAME }}"
  ALT: [ "*.{{ ACME_DOMAIN_NAME }}" ]
ACME_ENVIRONMENT_VARS:
  HE_Username: "{{ ACME_HE_USERNAME }}"
  HE_Password: "{{ ACME_HE_PASSWORD }}"
ACME_CERT_DIR: "/etc/LetsEncrypt/{{ ACME_DOMAINS.PRIMARY }}"
ACME_CERT_FILE_PATH: "{{ ACME_CERT_DIR }}/{{ ACME_DOMAINS.PRIMARY }}.crt"
ACME_KEY_FILE_PATH: "{{ ACME_CERT_DIR }}/{{ ACME_DOMAINS.PRIMARY }}.key"
ACME_CA_FILE_PATH: "{{ ACME_CERT_DIR }}/{{ ACME_DOMAINS.PRIMARY }}-ca.crt"
ACME_FULLCHAIN_FILE_PATH: "{{ ACME_CERT_DIR }}/{{ ACME_DOMAINS.PRIMARY }}-fullchain.crt"
ACME_ISSUE_COMMAND: |
  {{ ACME_SHELL_SCRIPT }} --server letsencrypt --issue --dns dns_he --config-home {{ ACME_HOME_DIR }} --log {{ ACME_LOG_FILE }} --cert-file {{ ACME_CERT_FILE_PATH }} --key-file {{ ACME_KEY_FILE_PATH }} --ca-file {{ ACME_CA_FILE_PATH }} --fullchain-file {{ ACME_FULLCHAIN_FILE_PATH }} {% if ACME_DOMAINS.PRIMARY is defined and ACME_DOMAINS.PRIMARY | length %}-d {{ ACME_DOMAINS.PRIMARY }}{% endif %}{% if ACME_DOMAINS.ALT is defined and ACME_DOMAINS.ALT | length %}{% for domain in ACME_DOMAINS.ALT %} -d "{{ domain }}"{% endfor %}{% endif %}
ACME_RENEW_CRON_COMMAND: |
  {{ ACME_SHELL_SCRIPT }} --cron --home {{ ACME_HOME_DIR }} --log {{ ACME_LOG_FILE }}

# grafana variables
GRAFANA_HTTP_ADDR: 127.0.0.1
GRAFANA_HTTP_PORT: 3001
GRAFANA_PLUGINS: "ntop-ntopng-datasource"
