name: Build PowerDNS Container Image
on:
  push:
    branches:
      - main
    paths:
      - "docker/powerdns/Dockerfile"
      - "docker/powerdns/pdns.sh"
      - "docker/powerdns/pdns.conf.template"
      - "docker/powerdns/recursor.conf.template"
      - ".github/workflows/powerdns-container-image-build.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: docker/powerdns/
          push: true
          tags: "${{ secrets.DOCKER_HUB_USERNAME }}/powerdns:latest,${{ secrets.DOCKER_HUB_USERNAME }}/powerdns:4.x"
