---
- name: Setup Firewall
  hosts: all
  gather_facts: yes
  become: True
  roles:
    - role: linux_common
      when: RUN_LINUX_COMMON is defined and RUN_LINUX_COMMON
    - role: motd
      when: RUN_MOTD is defined and RUN_MOTD
    # redis
    - role: podman
      PODMAN_VOLUMES: "{{ REDIS_CONFIG.VOLUMES }}"
      PODMAN_KUBE_POD_MANIFESTS: "{{ REDIS_CONFIG.PODS }}"
      PODMAN_KUBE_FILE: "{{ REDIS_CONFIG.KUBE_FILE }}"
      when: RUN_REDIS is defined and RUN_REDIS
    # ntopng
    - role: podman
      PODMAN_VOLUMES: "{{ NTOP_CONFIG.VOLUMES }}"
      PODMAN_KUBE_CONFIGMAP_MANIFESTS: "{{ NTOP_CONFIG.CONFIGMAPS }}"
      PODMAN_KUBE_POD_MANIFESTS: "{{ NTOP_CONFIG.PODS }}"
      PODMAN_KUBE_FILE: "{{ NTOP_CONFIG.KUBE_FILE }}"
      when: RUN_NTOPNG is defined and RUN_NTOPNG
    # firewall
    - role: firewall
      when: RUN_FIREWALL is defined and RUN_FIREWALL
