---
- name: Setup Firewall
  hosts: all
  gather_facts: yes
  become: True
  roles:
    - role: linux_common
      when: RUN_LINUX_COMMON is defined and RUN_LINUX_COMMON
    - role: motd
      when: RUN_MOTD is defined and RUN_MOTD
    - role: acme
      when: RUN_ACME is defined and RUN_ACME
    - role: firewall
      when: RUN_FIREWALL is defined and RUN_FIREWALL
    # redis
    - role: podman
      PODMAN_SERVICE_NAME: "{{ REDIS_SERVICE_NAME }}"
      PODMAN_VOLUMES: "{{ REDIS_CONFIG.VOLUMES }}"
      PODMAN_KUBE_POD_MANIFESTS: "{{ REDIS_CONFIG.PODS }}"
      PODMAN_KUBE_FILE: "{{ REDIS_CONFIG.KUBE_FILE }}"
      when: RUN_REDIS is defined and RUN_REDIS
    # mysql
    - role: podman
      PODMAN_SERVICE_NAME: "{{ MARIADB_SERVICE_NAME }}"
      PODMAN_VOLUMES: "{{ MARIADB_CONFIG.VOLUMES }}"
      PODMAN_KUBE_SECRET_MANIFESTS: "{{ MARIADB_CONFIG.SECRETS }}"
      PODMAN_KUBE_POD_MANIFESTS: "{{ MARIADB_CONFIG.PODS }}"
      PODMAN_KUBE_FILE: "{{ MARIADB_CONFIG.KUBE_FILE }}"
      when: RUN_MARIADB is defined and RUN_MARIADB
    - role: mysql_db_users
      when: RUN_MARIADB is defined and RUN_MARIADB
    # influxdb
    - role: podman
      PODMAN_SERVICE_NAME: "{{ INFLUXDB_SERVICE_NAME }}"
      PODMAN_VOLUMES: "{{ INFLUXDB_CONFIG.VOLUMES }}"
      PODMAN_KUBE_CONFIGMAP_MANIFESTS: "{{ INFLUXDB_CONFIG.CONFIGMAPS }}"
      PODMAN_KUBE_SECRET_MANIFESTS: "{{ INFLUXDB_CONFIG.SECRETS }}"
      PODMAN_KUBE_POD_MANIFESTS: "{{ INFLUXDB_CONFIG.PODS }}"
      PODMAN_KUBE_FILE: "{{ INFLUXDB_CONFIG.KUBE_FILE }}"
      when: RUN_INFLUXDB is defined and RUN_INFLUXDB
    - role: influxdb_db_users
      when: RUN_INFLUXDB is defined and RUN_INFLUXDB
    # ntopng
    - role: podman
      PODMAN_SERVICE_NAME: "{{ NTOPNG_SERVICE_NAME }}"
      PODMAN_VOLUMES: "{{ NTOP_CONFIG.VOLUMES }}"
      PODMAN_KUBE_CONFIGMAP_MANIFESTS: "{{ NTOP_CONFIG.CONFIGMAPS }}"
      PODMAN_KUBE_POD_MANIFESTS: "{{ NTOP_CONFIG.PODS }}"
      PODMAN_KUBE_FILE: "{{ NTOP_CONFIG.KUBE_FILE }}"
      PODMAN_SERVICE_DEPENDENCIES: "{{ NTOP_CONFIG.DEPENDENCIES }}"
      when: RUN_NTOPNG is defined and RUN_NTOPNG
    # grafana
    - role: podman
      PODMAN_SERVICE_NAME: "{{ GRAFANA_SERVICE_NAME }}"
      PODMAN_VOLUMES: "{{ GRAFANA_CONFIG.VOLUMES }}"
      PODMAN_KUBE_CONFIGMAP_MANIFESTS: "{{ GRAFANA_CONFIG.CONFIGMAPS }}"
      PODMAN_KUBE_SECRET_MANIFESTS: "{{ GRAFANA_CONFIG.SECRETS }}"
      PODMAN_KUBE_POD_MANIFESTS: "{{ GRAFANA_CONFIG.PODS }}"
      PODMAN_KUBE_FILE: "{{ GRAFANA_CONFIG.KUBE_FILE }}"
      PODMAN_SERVICE_DEPENDENCIES: "{{ GRAFANA_CONFIG.DEPENDENCIES }}"
      when: RUN_GRAFANA is defined and RUN_GRAFANA
    # powerdns
    - role: podman
      PODMAN_SERVICE_NAME: "{{ POWERDNS_SERVICE_NAME }}"
      PODMAN_KUBE_CONFIGMAP_MANIFESTS: "{{ POWERDNS_CONFIG.CONFIGMAPS }}"
      PODMAN_KUBE_SECRET_MANIFESTS: "{{ POWERDNS_CONFIG.SECRETS }}"
      PODMAN_KUBE_POD_MANIFESTS: "{{ POWERDNS_CONFIG.PODS }}"
      PODMAN_KUBE_FILE: "{{ POWERDNS_CONFIG.KUBE_FILE }}"
      PODMAN_SERVICE_DEPENDENCIES: "{{ POWERDNS_CONFIG.DEPENDENCIES }}"
      when: RUN_POWERDNS is defined and RUN_POWERDNS
    - role: pdns_manager
      when: RUN_POWERDNS is defined and RUN_POWERDNS
    # kea
    - role: podman
      PODMAN_SERVICE_NAME: "{{ KEA_SERVICE_NAME }}"
      PODMAN_VOLUMES: "{{ KEA_CONFIG.VOLUMES }}"
      PODMAN_KUBE_CONFIGMAP_MANIFESTS: "{{ KEA_CONFIG.CONFIGMAPS }}"
      PODMAN_KUBE_SECRET_MANIFESTS: "{{ KEA_CONFIG.SECRETS }}"
      PODMAN_KUBE_POD_MANIFESTS: "{{ KEA_CONFIG.PODS }}"
      PODMAN_KUBE_FILE: "{{ KEA_CONFIG.KUBE_FILE }}"
      PODMAN_SERVICE_DEPENDENCIES: "{{ KEA_CONFIG.DEPENDENCIES }}"
      when: RUN_KEA is defined and RUN_KEA
    - role: kea_hosts_manager
      when: RUN_KEA is defined and RUN_KEA
    # omada
    - role: podman
      PODMAN_SERVICE_NAME: "{{ OMADA_SERVICE_NAME }}"
      PODMAN_VOLUMES: "{{ OMADA_CONFIG.VOLUMES }}"
      PODMAN_KUBE_CONFIGMAP_MANIFESTS: "{{ OMADA_CONFIG.CONFIGMAPS }}"
      PODMAN_KUBE_POD_MANIFESTS: "{{ OMADA_CONFIG.PODS }}"
      PODMAN_KUBE_FILE: "{{ OMADA_CONFIG.KUBE_FILE }}"
      when: RUN_OMADA is defined and RUN_OMADA
    # nginx
    - role: podman
      PODMAN_SERVICE_NAME: "{{ NGINX_SERVICE_NAME }}"
      PODMAN_KUBE_CONFIGMAP_MANIFESTS: "{{ NGINX_CONFIG.CONFIGMAPS }}"
      PODMAN_KUBE_POD_MANIFESTS: "{{ NGINX_CONFIG.PODS }}"
      PODMAN_KUBE_FILE: "{{ NGINX_CONFIG.KUBE_FILE }}"
      PODMAN_SERVICE_DEPENDENCIES: "{{ NGINX_CONFIG.DEPENDENCIES }}"
      when: RUN_NGINX is defined and RUN_NGINX
